# Generated by Django 5.2.7 on 2025-10-13 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template', models.CharField(choices=[('freeform', 'Freeform Container')], default='freeform', max_length=32)),
                ('container_image', models.ImageField(upload_to='mockups/containers/')),
                ('design_image', models.ImageField(upload_to='mockups/designs/')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='mockups/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_mockups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
