# Generated by Django 5.1.13 on 2025-10-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_packagemockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemockup',
            name='design_pos_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='packagemockup',
            name='design_pos_y',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='packagemockup',
            name='design_rotation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packagemockup',
            name='design_scale',
            field=models.FloatField(default=60.0),
        ),
        migrations.AddField(
            model_name='packagemockup',
            name='mask_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/masks/'),
        ),
    ]
