# Generated by Django 5.1.13 on 2025-10-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_packagemockup_mask_feather_packagemockup_mask_invert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemockup',
            name='design_pos_x',
            field=models.FloatField(blank=True, default=50.0),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='design_pos_y',
            field=models.FloatField(blank=True, default=50.0),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='design_rotation',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='design_scale',
            field=models.FloatField(blank=True, default=60.0),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='mask_feather',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='mask_opacity',
            field=models.FloatField(blank=True, default=100.0),
        ),
    ]
