# Generated by Django 5.2.7 on 2025-10-16 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_reques_created_96effa_idx'), models.Index(fields=['country'], name='core_reques_country_91a7a5_idx'), models.Index(fields=['region'], name='core_reques_region_450877_idx'), models.Index(fields=['user'], name='core_reques_user_id_a6a30c_idx')],
            },
        ),
    ]
