# Generated by Django 5.1.13 on 2025-10-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_packagemockup_design_pos_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemockup',
            name='mask_feather',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packagemockup',
            name='mask_invert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagemockup',
            name='mask_opacity',
            field=models.FloatField(default=100.0),
        ),
    ]
