# Generated by Django 5.2.7 on 2025-10-16 15:18

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_packagemockup_design_pos_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemockup',
            name='container_image',
            field=models.ImageField(upload_to='mockups/containers/', validators=[projects.models.MaxSizeValidator(15), projects.models.ExtensionValidator({'jpeg', 'jpg', 'png', 'webp'})]),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='design_image',
            field=models.ImageField(upload_to='mockups/designs/', validators=[projects.models.MaxSizeValidator(15), projects.models.ExtensionValidator({'jpeg', 'jpg', 'png', 'webp'})]),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/generated/', validators=[projects.models.MaxSizeValidator(20), projects.models.ExtensionValidator({'jpeg', 'jpg', 'png', 'webp'})]),
        ),
        migrations.AlterField(
            model_name='packagemockup',
            name='mask_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/masks/', validators=[projects.models.MaxSizeValidator(10), projects.models.ExtensionValidator({'png', 'webp'})]),
        ),
        migrations.AlterField(
            model_name='project',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='project_audio/', validators=[projects.models.MaxSizeValidator(100), projects.models.ExtensionValidator({'aac', 'flac', 'mp3', 'ogg', 'wav'})]),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/', validators=[projects.models.MaxSizeValidator(10), projects.models.ExtensionValidator({'jpeg', 'jpg', 'png', 'webp'})]),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='project_video/', validators=[projects.models.MaxSizeValidator(300), projects.models.ExtensionValidator({'mkv', 'mov', 'mp4', 'webm'})]),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='project_files/', validators=[projects.models.MaxSizeValidator(100), projects.models.ExtensionValidator({'ai', 'doc', 'docx', 'pdf', 'ppt', 'pptx', 'psd', 'rar', 'txt', 'xls', 'xlsx', 'zip'})]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/', validators=[projects.models.MaxSizeValidator(10), projects.models.ExtensionValidator({'jpeg', 'jpg', 'png', 'webp'})]),
        ),
    ]
